[metadata]
name = mp2hudcolor
version = 1.0.14
author = toasterparty
author_email = toasterparty@derpymail.org
url = https://github.com/toasterparty/mp2hudcolor
description = Modifies an existing NTWK file for Metroid Prime 2: Echoes and changing the color of the HUD
long_description = file: README.md
long_description_content_type = text/markdown

license = MIT
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
packages =
    mp2hudcolor
install_requires =

zip_safe = True
python_requires = >=3.10
